services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust  # This disables password auth
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ${REGISTRY}/${DOCKER_IMAGE}:latest
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - "./uploads:/app/uploads"
    depends_on:
      database:
        condition: service_healthy
    environment:
      NITRO_HOST: "0.0.0.0"

      NUXT_DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NUXT_SITE_NAME: ${NUXT_SITE_NAME}
      NUXT_SITE_URL: ${NUXT_SITE_URL}

      NUXT_OAUTH_GITHUB_CLIENT_ID: ${NUXT_OAUTH_GITHUB_CLIENT_ID}
      NUXT_OAUTH_GITHUB_CLIENT_SECRET: ${NUXT_OAUTH_GITHUB_CLIENT_SECRET}
      NUXT_OAUTH_GITHUB_REDIRECT_URL: ${NUXT_OAUTH_GITHUB_REDIRECT_URL}

      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
      NUXT_AUTHORIZED_EMAIL: ${NUXT_AUTHORIZED_EMAIL}

      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}

      NUXT_OG_API_TOKEN: ${NUXT_OG_API_TOKEN}
      NUXT_OG_TEMPLATE_URL: ${NUXT_OG_TEMPLATE_URL}

    restart: unless-stopped
    networks:
      - nginx
      - app-network

  migration:
    image: ${REGISTRY}/${DOCKER_IMAGE}-migration:latest
    environment:
      DB_HOST: database
      DB_PORT: 5432
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      NUXT_DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

secrets:
  sentry_auth_token:
    environment: SENTRY_AUTH_TOKEN

networks:
  app-network:
    driver: bridge

  nginx:
    external: true
    name: nginx
