name: Deploy Website
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: neikow/${{ github.repository }}

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: runner
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}"

      - name: Build and push migration image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: migration
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}-migration:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Redeploy via Portainer Hook
    runs-on: ubuntu-latest
    environment: Production
    needs: build-and-push
    steps:
      - name: Trigger Portainer redeploy hook
        run: curl --fail --show-error --silent -X POST "${{ secrets.DEPLOYMENT_HOOK }}"
